# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
commands:
    print_pipeline_id:
      description: "A very simple command for demonstration purposes"
      parameters:
        to:
          type: string
          default: cat $CIRCLE_WORKFLOW_ID
      steps:
        - run: echo << parameters.to >>
        
jobs:

  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "helo output"
          command: echo "text to output here -- this ouput stanley --" > output.txt
      - persist_to_workspace:
          root: .
          paths:
            - output.txt
  
  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: cat output.txt

  to_print_command:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  node-workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires: [save_hello_world_output]
      - to_print_command:
          requires: [print_output_file]
